repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy-check
        name: mypy check
        entry: bash -c "cd src && python -m mypy dokployer --config-file ../mypy.ini --explicit-package-bases"
        language: system
        pass_filenames: false
        types: [python]

      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        types: [python]
