"""Constants and environment variable names for dokployer."""

from __future__ import annotations

from enum import StrEnum


class ComposeStatus(StrEnum):
    """Possible states for a compose deployment."""

    DONE = "done"
    ERROR = "error"
    RUNNING = "running"
    UNKNOWN = "unknown"


DOKPLOY_URL = "DOKPLOY_URL"
DOKPLOY_API_KEY = "DOKPLOY_API_KEY"
DOKPLOY_ENV_ID = "DOKPLOY_ENV_ID"
DOKPLOY_APP_ID = "DOKPLOY_APP_ID"
DOKPLOY_APP_NAME = "DOKPLOY_APP_NAME"

DEPLOY_POLL_INTERVAL = "DEPLOY_POLL_INTERVAL"
DEPLOY_POLL_TIMEOUT = "DEPLOY_POLL_TIMEOUT"
STACK_POLL_INTERVAL = "STACK_POLL_INTERVAL"
STACK_POLL_TIMEOUT = "STACK_POLL_TIMEOUT"

DEFAULT_HTTP_TIMEOUT_SECONDS = 120
DEFAULT_DEPLOY_POLL_INTERVAL_SECONDS = 5
DEFAULT_DEPLOY_POLL_TIMEOUT_SECONDS = 60
DEFAULT_STACK_POLL_INTERVAL_SECONDS = 5
DEFAULT_STACK_POLL_TIMEOUT_SECONDS = 300

COMPOSE_API_PATH = "/api/compose.one"
COMPOSE_CREATE_API_PATH = "/api/compose.create"
COMPOSE_UPDATE_API_PATH = "/api/compose.update"
COMPOSE_DEPLOY_API_PATH = "/api/compose.deploy"
ENVIRONMENT_API_PATH = "/api/environment.one"
